name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install ARM GCC Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '4.0.0'
      - name: Install Python dependencies
        run: pip install pyelftools

      
      - name: Configure Debug
        run: cmake -S . -B build/debug -DCMAKE_BUILD_TYPE=Debug
      - name: Build Debug
        run: cmake --build build/debug

      - name: Configure  Release
        run: cmake -S . -B build/release -DCMAKE_BUILD_TYPE=Debug

      - name: Build Release
        run: cmake --build build/release

